### ISSUE TITLE
Unable to get the integration

### ISSUE THREAD

**Issue by sandrybridge** [eelcohn/home-assistant-ddwrt#13]
Hi, I've installed the integration (the custom_components folder was just there due to a previous installation of hacs).
I can't see the integration in the UI and when I try to get dd-wrt configured with the yaml I've got  this error in the reboot of the server  

Logger: homeassistant.setup
Source: setup.py:179
First occurred: 11:20:04 (1 occurrences)
Last logged: 11:20:04
Setup failed for ddwrt: No setup or config entry setup function defined.

tx a lot for your time

**Comment by zsamiatt** [comment]
I can not restart.

Component error: ddwrt - cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by eelcohn** [comment]
Should be fixed in v1.1.3
