### ISSUE TITLE
Setup failed for ddwrt: Unable to import component: cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### ISSUE THREAD

**Issue by acdcnow** [eelcohn/home-assistant-ddwrt#14]
tried to setup the custom component DDWRT on HA 2021.11.5 but that failed with the error:

Setup failed for ddwrt: Unable to import component: cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Installed it via HACS and then used a simple config. No uPnP server should be used.

even the flow config on the integration page via ddwrt is not working.

Error
Config flow could not be loaded

would be great if you could have a look into that issue.

**Comment by acdcnow** [comment]
looks like that in const.py a attribute is used that is not working...

from homeassistant.const import (
    ATTR_DEVICE_CLASS,
    ATTR_ICON,
    ATTR_NAME,
    ATTR_UNIT_OF_MEASUREMENT,
    DATA_KILOBYTES,
    DATA_MEGABYTES,
    DATA_RATE_MEGABITS_PER_SECOND,
    DEVICE_CLASS_SIGNAL_STRENGTH,
    DEVICE_CLASS_TEMPERATURE,
    LENGTH_METERS,
    TEMP_CELSIUS,
    TIME_MICROSECONDS,
    TIME_MINUTES,
    VOLT, -->!
)
......

    "voltage": {
        ATTR_NAME: "Voltage",
        ATTR_UNIT_OF_MEASUREMENT: VOLT, --<!!
        ATTR_ICON: "mdi:current-dc",
        ATTR_DEVICE_CLASS: None,

**Comment by DrHerbalist** [comment]
I ended up updating line 20 and line 310, replacing 'VOLT' with 'ELECTRIC_POTENTIAL_VOLT'.
Seems to have fixed it.

**Comment by eelcohn** [comment]
Thanks @MarcusVinter 
It should be fixed in v1.1.3
